language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - jruby-19mode
  - rbx-2
before_install:
  - gem update --system
  - gem update bundler
install: 'bundle install'
script: 'bundle exec rake'
cache: bundler
